# Generated by Django 4.0.4 on 2022-05-19 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 7, 16, 32, 728019, tzinfo=utc)),
        ),
    ]
